package com.sindhi.urdu.english.keybad.sindhikeyboard.utils


object RemoteConfigConst {
    const val ACTION = "ACTION"
    const val DESTINATION1 = "DESTINATION1"
    const val DESTINATION2 = "DESTINATION2"
    const val DESTINATION3 = "DESTINATION3"
    const val FROM_SHORTCUT = "FROM_SHORTCUT"

    const val INTER_OVER_ALL = "INTER_OVER_ALL"
    const val NATIVE_OVER_ALL = "NATIVE_OVER_ALL"
    const val NATIVE_THEMES = "NATIVE_THEMES"
    const val NATIVE_HOME = "NATIVE_HOME"
    const val NATIVE_CONVERSATION = "NATIVE_CONVERSATION"
    const val BANNER_INSIDE = "BANNER_INSIDE"
    const val NATIVE_KEYPAD = "NATIVE_KEYPAD"
    const val REMOTE_CONFIG = "RemoteConfig"


    // SOT-Ads-Visibility-Config
    const val RESUME_INTER_SPLASH = "RESUME_INTER_SPLASH"
    const val RESUME_OVERALL = "RESUME_OVERALL"
    const val KEY_SELECTED_LANGUAGE_CODE = "KEY_SELECTED_LANGUAGE_CODE"

    const val BANNER_SPLASH = "BANNER_SPLASH"
    const val NATIVE_LANGUAGE_1 = "NATIVE_LANGUAGE_1"
    const val NATIVE_LANGUAGE_2 = "NATIVE_LANGUAGE_2"
    const val NATIVE_SURVEY_1 = "NATIVE_SURVEY_1"
    const val NATIVE_SURVEY_2 = "NATIVE_SURVEY_2"
    const val NATIVE_WALKTHROUGH_1 = "NATIVE_WALKTHROUGH_1"
    const val NATIVE_WALKTHROUGH_FULLSCR = "NATIVE_WALKTHROUGH_FULLSCR"
    const val NATIVE_WALKTHROUGH_3 = "NATIVE_WALKTHROUGH_3"
    const val NATIVE_WALKTHROUGH_2 = "NATIVE_WALKTHROUGH_2"

    //    const val ADMOB_INTER_LET_START = "ADMOB_INTER_LET_START"
    const val INTERSTITIAL_LETS_START = "INTERSTITIAL_LETS_START"
    const val IS_PURCHASED = "IS_PURCHASED"



    const val NATIVE_UNINSTALL = "NATIVE_UNINSTALL"
    const val NATIVE_SURVEY = "NATIVE_SURVEY"
    const val AD_ID_NATIVE_UNINSTAL = "AD_ID_NATIVE_UNINSTAL"
    const val AD_ID_NATVE_SURVAY = "AD_ID_NATVE_SURVAY"


    const val BANNER_STICKER = "BANNER_STICKER"
    const val NATIVE_STICKERS = "NATIVE_STICKERS"
    const val BANNER_STICKER_DETAILS = "BANNER_STICKER_DETAILS"
    const val NATIVE_STICKERS_DETAILS = "NATIVE_STICKERS_DETAILS"


    const val OVERALL_BANNER_RELOADING = "OVERALL_BANNER_RELOADING"
    const val OVERALL_NATIVE_RELOADING = "OVERALL_NATIVE_RELOADING"
    const val INTERSTITIAL_STICKER_ENTER = "INTERSTITIAL_STICKER_ENTER"
    const val KEYPAD_AD_VISIBILITY = "KEYPAD_AD_VISIBILITY"
    const val KEYPAD_AD_MEDIATION = "KEYPAD_AD_MEDIATION"

    const val TIMER_NATIVE_F_SRC = "TIMER_NATIVE_F_SRC"
    const val BANNER_POETRY = "BANNER_POETRY"
    const val NATIVE_TEXT_TRANSLATOR = "NATIVE_TEXT_TRANSLATOR"
    const val BANNER_THEMES_LIST = "BANNER_THEMES_LIST"
    const val ADS_BANNER_THEMES_TEST = "ADS_BANNER_THEMES_TEST"
    const val ADS_BANNER_HISTORY = "ADS_BANNER_HISTORY"
    const val ADMOB_SPLASH_INTERSTITIAL = "ADMOB_SPLASH_INTERSTITIAL"
    const val ADMOB_SPLASH_RESUME = "ADMOB_SPLASH_RESUME"
    const val ADMOB_BANNER_SPLASH = "ADMOB_BANNER_SPLASH"
    const val ADMOB_NATIVE_LANGUAGE_1 = "ADMOB_NATIVE_LANGUAGE_1"
    const val ADMOB_NATIVE_LANGUAGE_2 = "ADMOB_NATIVE_LANGUAGE_2"
    const val ADMOB_NATIVE_SURVEY_1 = "ADMOB_NATIVE_SURVEY_1"
    const val ADMOB_NATIVE_SURVEY_2 = "ADMOB_NATIVE_SURVEY_2"
    const val ADMOB_NATIVE_WALKTHROUGH_1 = "ADMOB_NATIVE_WALKTHROUGH_1"
    const val ADMOB_NATIVE_WALKTHROUGH_2 = "ADMOB_NATIVE_WALKTHROUGH_2"
    const val ADMOB_NATIVE_WALKTHROUGH_FULLSCR = "ADMOB_NATIVE_WALKTHROUGH_FULLSCR"
    const val ADMOB_NATIVE_WALKTHROUGH_3 = "ADMOB_NATIVE_WALKTHROUGH_3"
    const val ADMOB_INTERSTITIAL_LETS_START = "ADMOB_INTERSTITIAL_LETS_START"
}