package com.sindhi.urdu.english.keybad.sindhikeyboard.utils


object RemoteConfigConst {

    /**Ads Form Remote Config**/
    /**FOF_Ads_Config**/
    const val AD_CONFIG_SPLASH_INTERSTITIAL = "AD_CONFIG_SPLASH_INTERSTITIAL"
    const val AD_CONFIG_SPLASH_RESUME = "AD_CONFIG_SPLASH_RESUME"
    const val AD_CONFIG_BANNER_SPLASH = "AD_CONFIG_BANNER_SPLASH"
    const val AD_CONFIG_NATIVE_LANGUAGE_1 = "AD_CONFIG_NATIVE_LANGUAGE_1"
    const val AD_CONFIG_NATIVE_LANGUAGE_2 = "AD_CONFIG_NATIVE_LANGUAGE_2"
    const val AD_CONFIG_NATIVE_SURVEY_1 = "AD_CONFIG_NATIVE_SURVEY_1"
    const val AD_CONFIG_INTERSTITIAL_LETS_START = "AD_CONFIG_INTERSTITIAL_LETS_START"
    const val AD_CONFIG_NATIVE_SURVEY_2 = "AD_CONFIG_NATIVE_SURVEY_2"
    const val AD_CONFIG_NATIVE_WALKTHROUGH_1 = "AD_CONFIG_NATIVE_WALKTHROUGH_1"
    const val AD_CONFIG_NATIVE_WALKTHROUGH_2 = "AD_CONFIG_NATIVE_WALKTHROUGH_2"
    const val AD_CONFIG_NATIVE_WALKTHROUGH_FULLSCR = "AD_CONFIG_NATIVE_WALKTHROUGH_FULLSCR"
    const val AD_CONFIG_NATIVE_WALKTHROUGH_3 = "ADMOB_NATIVE_WALKTHROUGH_3"
    /**InsideAppAds**/

    const val INTER_OVER_ALL = "INTER_OVER_ALL"
    const val NATIVE_OVER_ALL = "NATIVE_OVER_ALL"
    const val NATIVE_KEY_PAD = "NATIVE_KEY_PAD"
    const val NATIVE_THEMES = "NATIVE_THEMES"
    const val NATIVE_HOME = "NATIVE_HOME"
    const val NATIVE_CONVERSATION = "NATIVE_CONVERSATION"
    const val BANNER_INSIDE = "BANNER_INSIDE"
    const val RESUME_OVER_ALL = "RESUME_OVER_ALL"
    const val NATIVE_KEYPAD = "NATIVE_KEYPAD"
    const val IS_FIRST_TIME = "IS_FIRST_TIME"


    // SOT-Ads-Visibility-Config
    const val RESUME_INTER_SPLASH = "RESUME_INTER_SPLASH"
    const val RESUME_OVERALL = "RESUME_OVERALL"
    const val KEY_SELECTED_LANGUAGE_CODE = "KEY_SELECTED_LANGUAGE_CODE"

    const val BANNER_SPLASH = "BANNER_SPLASH"
    const val NATIVE_LANGUAGE_1 = "NATIVE_LANGUAGE_1"
    const val NATIVE_LANGUAGE_2 = "NATIVE_LANGUAGE_2"
    const val NATIVE_SURVEY_1 = "NATIVE_SURVEY_1"
    const val NATIVE_SURVEY_2 = "NATIVE_SURVEY_2"
    const val NATIVE_WALKTHROUGH_1 = "NATIVE_WALKTHROUGH_1"
    const val NATIVE_WALKTHROUGH_FULLSCR = "NATIVE_WALKTHROUGH_FULLSCR"
    const val NATIVE_WALKTHROUGH_3 = "NATIVE_WALKTHROUGH_3"
    const val NATIVE_WALKTHROUGH_2 = "NATIVE_WALKTHROUGH_2"

    //    const val ADMOB_INTER_LET_START = "ADMOB_INTER_LET_START"
    const val INTERSTITIAL_LETS_START = "INTERSTITIAL_LETS_START"
    const val IS_PURCHASED = "IS_PURCHASED"


    // SOT-Ads-Mediation-Config
    const val RESUME_INTER_SPLASH_MED = "RESUME_INTER_SPLASH_MED"
    const val RESUME_OVERALL_MED = "RESUME_OVERALL_MED"
    const val BANNER_SPLASH_MED = "BANNER_SPLASH_MED"
    const val NATIVE_LANGUAGE_1_MED = "NATIVE_LANGUAGE_1_MED"
    const val NATIVE_LANGUAGE_2_MED = "NATIVE_LANGUAGE_2_MED"
    const val NATIVE_SURVEY_1_MED = "NATIVE_SURVEY_1_MED"
    const val NATIVE_SURVEY_2_MED = "NATIVE_SURVEY_2_MED"
    const val NATIVE_WALKTHROUGH_1_MED = "NATIVE_WALKTHROUGH_1_MED"
    const val NATIVE_WALKTHROUGH_FULLSCR_MED = "NATIVE_WALKTHROUGH_FULLSCR_MED"
    const val NATIVE_WALKTHROUGH_3_MED = "NATIVE_WALKTHROUGH_3_MED"
    const val NATIVE_WALKTHROUGH_2_MED = "NATIVE_WALKTHROUGH_2_MED"

    //    const val ADMOB_INTER_LET_START_MED = "ADMOB_INTER_LET_START_MED"
    const val INTERSTITIAL_LETS_START_MED = "INTERSTITIAL_LETS_START_MED"
    const val BANNER_STICKER = "BANNER_STICKER"
    const val NATIVE_STICKERS = "NATIVE_STICKERS"
    const val BANNER_STICKER_DETAILS = "BANNER_STICKER_DETAILS"
    const val NATIVE_STICKERS_DETAILS = "NATIVE_STICKERS_DETAILS"


    const val OVERALL_BANNER_RELOADING = "OVERALL_BANNER_RELOADING"
    const val OVERALL_NATIVE_RELOADING = "OVERALL_NATIVE_RELOADING"
    const val INTERSTITIAL_STICKER_ENTER = "INTERSTITIAL_STICKER_ENTER"
    const val KEYPAD_AD_VISIBILITY = "KEYPAD_AD_VISIBILITY"
    const val KEYPAD_AD_MEDIATION = "KEYPAD_AD_MEDIATION"

    const val TIMER_NATIVE_F_SRC = "TIMER_NATIVE_F_SRC"
    const val BANNER_POETRY = "BANNER_POETRY"
    const val ADS_BANNER_THEMES_TEST = "ADS_BANNER_THEMES_TEST"
    const val ADS_BANNER_HISTORY = "ADS_BANNER_HISTORY"
    const val ADMOB_SPLASH_INTERSTITIAL = "ADMOB_SPLASH_INTERSTITIAL"
    const val ADMOB_SPLASH_RESUME = "ADMOB_SPLASH_RESUME"
    const val ADMOB_BANNER_SPLASH = "ADMOB_BANNER_SPLASH"
    const val ADMOB_NATIVE_LANGUAGE_1 = "ADMOB_NATIVE_LANGUAGE_1"
    const val ADMOB_NATIVE_LANGUAGE_2 = "ADMOB_NATIVE_LANGUAGE_2"
    const val ADMOB_NATIVE_SURVEY_1 = "ADMOB_NATIVE_SURVEY_1"
    const val ADMOB_NATIVE_SURVEY_2 = "ADMOB_NATIVE_SURVEY_2"
    const val ADMOB_NATIVE_WALKTHROUGH_1 = "ADMOB_NATIVE_WALKTHROUGH_1"
    const val ADMOB_NATIVE_WALKTHROUGH_2 = "ADMOB_NATIVE_WALKTHROUGH_2"
    const val ADMOB_NATIVE_WALKTHROUGH_FULLSCR = "ADMOB_NATIVE_WALKTHROUGH_FULLSCR"
    const val ADMOB_NATIVE_WALKTHROUGH_3 = "ADMOB_NATIVE_WALKTHROUGH_3"
    const val ADMOB_INTERSTITIAL_LETS_START = "ADMOB_INTERSTITIAL_LETS_START"
}