package com.sindhi.urdu.english.keybad.sindhikeyboard.ui.fragments.SpeechToText

import com.manual.mediation.library.sotadlib.data.Language
import com.sindhi.newvoicetyping.ui.Speechtotext.CountryCountry

object AllCountryListMe {
      fun getCountryList(): ArrayList<CountryCountry> {
            val arrayList = ArrayList<CountryCountry>()
            arrayList.add(CountryCountry("English (En)", Language.English.imageId, "en", "en-US"))
            arrayList.add(CountryCountry("Afrikaans (Afrikaans)", Language.Afrikaans.imageId, "af", "af-ZA"))
            arrayList.add(CountryCountry("Albanian (shqiptar)", Language.Albanian.imageId, "sq", "sq-AL"))
            arrayList.add(CountryCountry("Amharic (አማርኛ)", Language.Amharic.imageId, "am", "am-ET"))
            arrayList.add(CountryCountry("Arabic (العربية)", Language.Arabic.imageId, "ar", "ar-SA"))
            arrayList.add(CountryCountry("Armenian (հայերեն)", Language.Armenian.imageId, "hy", "hy-AM"))
            arrayList.add(CountryCountry("Azeerbaijani (Azərbaycan)", Language.Azerbaijani.imageId, "az", "az-AZ"))
            arrayList.add(CountryCountry("Basque (Euskara)", Language.Basque.imageId, "eu", "eu-ES"))
            arrayList.add(CountryCountry("Bengali (বাংলা)", Language.Bengali.imageId, "bn", "bn-BD"))
            arrayList.add(CountryCountry("Bosnian (Bosanski)", Language.Bosnian.imageId, "bs", "bs-BA"))
            arrayList.add(CountryCountry("Bulgarian (български)", Language.Bulgarian.imageId, "bg", "bg-BG"))
            arrayList.add(CountryCountry("Burmese (ဗမာ)", Language.Burmese.imageId, "my", "my-MM"))
            arrayList.add(CountryCountry("Catalan (Català)", Language.Catalan.imageId, "ca", "ca-ES"))
            arrayList.add(CountryCountry("Cebuano (Cebuano)", Language.Cebuano.imageId, "ceb", "ceb-PHL"))
            arrayList.add(CountryCountry("Chinese Simplified (中文简体)", Language.Chinese.imageId, "zh", "zh-CN"))
            arrayList.add(CountryCountry("Croatian (Croatian)", Language.Croatian.imageId, "hr", "hr-HR"))
            arrayList.add(CountryCountry("Czech (češki)", Language.Czech.imageId, "cs", "cs-CZ"))
            arrayList.add(CountryCountry("Danish (Danish)", Language.Danish.imageId, "da", "da-DK"))
            arrayList.add(CountryCountry("Dutch (Nederlands)", Language.Dutch.imageId, "nl", "nl-BE"))
            arrayList.add(CountryCountry("Esperanto (Esperanto)", Language.Esperanto.imageId, "eo", "eo-DZ"))
            arrayList.add(CountryCountry("Estonian (Estonian)", Language.Estonian.imageId, "et", "et-EE"))
            arrayList.add(CountryCountry("Filipino (Pilipino)", Language.Filipino.imageId, "fil", "fil-PH"))
            arrayList.add(CountryCountry("Finnish (Finnish)", Language.Finnish.imageId, "fi", "fi-FI"))
            arrayList.add(CountryCountry("French (français)", Language.French.imageId, "fr", "fr-FR"))
            arrayList.add(CountryCountry("Frisian (Frisian)", Language.Frisian.imageId, "fy", "fy-DEU"))
            arrayList.add(CountryCountry("Galician (Galician)", Language.Galician.imageId, "gl", "gl-ES"))
            arrayList.add(CountryCountry("Georgian (ქართული)", Language.Georgian.imageId, "ka", "ka-GE"))
            arrayList.add(CountryCountry("German (Deutsch)", Language.German.imageId, "de", "de-DE"))
            arrayList.add(CountryCountry("Greek (Ελληνικά)", Language.Greek.imageId, "el", "el-GR"))
            arrayList.add(CountryCountry("Gujarati (ગુજરાતી)", Language.Gujarati.imageId, "gu", "gu-IN"))
            arrayList.add(CountryCountry("Haitian (Ayisyen)", Language.Haitian.imageId, "ht", "ht-HTI"))
            arrayList.add(CountryCountry("Hawaiian (Ōlelo Hawaiʻi)", Language.Hawaiian.imageId, "haw", "haw-US"))
            arrayList.add(CountryCountry("Hindi (हिंदी)", Language.Hindi.imageId, "hi", "hi-IN"))
            arrayList.add(CountryCountry("Hmong (Hmoob)", Language.Hmong.imageId, "hmn", "hmn-Hm"))
            arrayList.add(CountryCountry("Hungarian (Magyar)", Language.Hungarian.imageId, "hu", "hu-HU"))
            arrayList.add(CountryCountry("Icelandic (izlandi)", Language.Icelandic.imageId, "is", "is-IS"))
            arrayList.add(CountryCountry("Indonesian (Indonesian)", Language.Indonesian.imageId, "id", "id-ID"))
            arrayList.add(CountryCountry("Italian (Italiano)", Language.Italian.imageId, "it", "it-IT"))
            arrayList.add(CountryCountry("Japanese (日本語)", Language.Japanese.imageId, "ja", "ja-JP"))
            arrayList.add(CountryCountry("Javanese (Basa jawa)", Language.Javanese.imageId, "jv", "jv-ID"))
            arrayList.add(CountryCountry("Kannada (ಕನ್ನಡ)", Language.Kannada.imageId, "kn", "kn-IN"))
            arrayList.add(CountryCountry("Khmer (ភាសាខ្មែរ)", Language.Khmer.imageId, "km", "km-IN"))
            arrayList.add(CountryCountry("Korean (한국어)", Language.Korean.imageId, "ko", "ko-KR"))
            arrayList.add(CountryCountry("Kurdish (Kurdî)", Language.Kurdish.imageId, "ku", "ku-KUR"))
            arrayList.add(CountryCountry("Kyrgyz (Кыргызча)", Language.Kyrgyz.imageId, "ky", "ky-KGZ"))
            arrayList.add(CountryCountry("Lao (ລາວ)", Language.Lao.imageId, "lo", "lo-LA"))
            arrayList.add(CountryCountry("Latvian (Latviešu valoda)", Language.Latvian.imageId, "lv", "lv-LV"))
            arrayList.add(CountryCountry("Lithuanian (Lietuvių)", Language.Lithuanian.imageId, "lt", "lt-LT"))
            arrayList.add(CountryCountry("Macedonian (Македонски)", Language.Macedonian.imageId, "mk", "mk-MK"))
            arrayList.add(CountryCountry("Malay (Bahasa Melayu)", Language.Malay.imageId, "ms", "ms-MY"))
            arrayList.add(CountryCountry("Malayalam (മലയാളം)", Language.Malayalam.imageId, "ml", "ml-IN"))
            arrayList.add(CountryCountry("Maltese (Malti)", Language.Maltese.imageId, "mt", "mt-MLT"))
            arrayList.add(CountryCountry("Marathi (मराठी)", Language.Marathi.imageId, "mr", "mr-IN"))
            arrayList.add(CountryCountry("Mongolian (Монгол хэл дээр)", Language.Mongolian.imageId, "mn", "mn-MN"))
            arrayList.add(CountryCountry("Myanmar (Myanmar)", Language.Myanmar.imageId, "my", "my-MMR"))
            arrayList.add(CountryCountry("Nepali (नेपाली)", Language.Nepali.imageId, "ne", "ne-NP"))
            arrayList.add(CountryCountry("Norwegian (norsk)", Language.Norwegian.imageId, "no", "no-NO"))
            arrayList.add(CountryCountry("Pashto (پښتو)", Language.Pashto.imageId, "ps", "ps-PK"))
            arrayList.add(CountryCountry("Persian (فارسي)", Language.Persian.imageId, "fa", "fa-FA"))
            arrayList.add(CountryCountry("Polish (Polskie)", Language.Polish.imageId, "pl", "pl-PL"))
            arrayList.add(CountryCountry("Portuguese (Português)", Language.Portuguese.imageId, "pt", "pt-BR"))
            arrayList.add(CountryCountry("Punjabi (ਪੰਜਾਬੀ)", Language.Punjabi.imageId, "pa", "pa-IN"))
            arrayList.add(CountryCountry("Romanian (Română)", Language.Romanian.imageId, "ro", "ro-RO"))
            arrayList.add(CountryCountry("Russian (русский)", Language.Russian.imageId, "ru", "ru-RU"))
            arrayList.add(CountryCountry("Samoan (Samoa)", Language.Samoan.imageId, "sm", "sm-WSM"))
            arrayList.add(CountryCountry("Scots (Scots)", Language.Scots.imageId, "gd", "gd-GBR"))
            arrayList.add(CountryCountry("Serbian (Српски)", Language.Serbian.imageId, "sr", "sr-RS"))
            arrayList.add(CountryCountry("Shona (Shona)", Language.Shona.imageId, "sn", "sn-SNA"))
            arrayList.add(CountryCountry("Sindhi (سنڌي)", Language.Sindhi.imageId, "sd", "sd-Pk"))
            arrayList.add(CountryCountry("Sinhala (සිංහල)", Language.Sinhala.imageId, "si", "si-LK"))
            arrayList.add(CountryCountry("Slovak (slovenský)", Language.Slovak.imageId, "sk", "sk-SK"))
            arrayList.add(CountryCountry("Slovenian (Slovenščina)", Language.Slovenian.imageId, "sl", "sl-SI"))
            arrayList.add(CountryCountry("Somali (Somali)", Language.Somali.imageId, "so-SOM", "so-SOM"))
            arrayList.add(CountryCountry("Spanish (Español)", Language.Spanish.imageId, "es", "es-US"))
            arrayList.add(CountryCountry("Sundanese (Sunda)", Language.Sundanese.imageId, "su", "su-ID"))
            arrayList.add(CountryCountry("Swahili (Swahili)", Language.Swahili.imageId, "sw", "sw-KE"))
            arrayList.add(CountryCountry("Swedish (svenska)", Language.Swedish.imageId, "sv", "sv-SE"))
            arrayList.add(CountryCountry("Tagalog (Tagalog)", Language.Tagalog.imageId, "tl", "tl-TGL"))
            arrayList.add(CountryCountry("Tajik (Тоҷикӣ)", Language.Tajik.imageId, "tg", "tg-TJK"))
            arrayList.add(CountryCountry("Tamil (தமிழ்)", Language.Tamil.imageId, "ta", "ta-IN"))
            arrayList.add(CountryCountry("Telugu (తెలుగు)", Language.Telugu.imageId, "te", "te-IN"))
            arrayList.add(CountryCountry("Thai (ไทย)", Language.Thai.imageId, "th", "th-TH"))
            arrayList.add(CountryCountry("Turkish (Türk)", Language.Turkish.imageId, "tr", "tr-TR"))
            arrayList.add(CountryCountry("Ukrainian (Українська)", Language.Ukrainian.imageId, "uk", "uk-UA"))
            arrayList.add(CountryCountry("Urdu (اردو)", Language.Urdu.imageId, "ur", "ur-PK"))
            arrayList.add(CountryCountry("Uzbek (O zbek)", Language.Uzbek.imageId, "uz", "uz-UZ"))
            arrayList.add(CountryCountry("Vietnamese (Tiếng Việt)", Language.Vietnamese.imageId, "vi", "vi-VN"))
            arrayList.add(CountryCountry("Welsh (Welsh)", Language.Welsh.imageId, "cy", "cy-GBR"))
            arrayList.add(CountryCountry("Xhosa (Xhosa)", Language.Xhosa.imageId, "xh", "xh-XHO"))
            arrayList.add(CountryCountry("Zulu (IsiZulu)", Language.Zulu.imageId, "zu", "zu-ZA"))
            return arrayList
      }
}